### ISSUE TITLE
Add support for CH340 based usb-serial converters that are popular on newer arduino knockoffs

### ISSUE THREAD

**Issue by RePeet13** [Kegbot/kegbot-android#110] opened 2016-03-23 20:25 UTC
I have a knockoff arduino mini based on this chipset, and I intend to use it as a kegboard, however kegtab does not recognize it. I know it works because I have verified in other Android arduino apps, so the problem is in this app/driver, not the kegboard/arduino itself. 

https://github.com/mik3y/usb-serial-for-android/pull/121 Seems to be a fix already implemented, yet waiting for someone to look and pull it. @mik3y or whoever is in charge of this now, please take a look and see how feasible (and easy) this solution is

**Comment by mik3y** [comment] 2016-09-11 22:44
@RePeet13 want to try a pre-release? I've no good way to test this, but, this build has the latest usb-serial-for-android changes. [Kegtab-v85.apk](https://kegbb-media.s3-us-west-2.amazonaws.com/original/1X/c74fe0fbe6fb5c288d880ec0068d18e51dcd5003.apk)

**Comment by RePeet13** [comment] 2016-09-16 15:42
I definitely can, but I just moved, so everything is packed away until mid
Oct. I'll update when I get set up again!

T

**Comment by angrypiratebrewing** [comment] 2017-12-12 19:40
Hi @mik3y , @RePeet13 
I realize this is 12+ months later... but I've recently been trying to get kegtab up and running using an arduino mega clone with the CH340 chip.

I've tested the above app and unfortunately it's not recognising the arduino/flow meter.

@RePeet13 - did you have any success getting this up and running?

**Comment by RePeet13** [comment] 2017-12-12 19:51
No worries! I never got a chance to actually test this, because I didnt
have a kegerator at the time. I am considering setting another one up, and
if I would use kegbot in conjunction with that. My main fear is that kegbot
isnt (or at least when I was trying a year or so ago) very active. @mik3y
have you been making progress on it lately?

T

**Comment by angrypiratebrewing** [comment] 2017-12-12 20:10
Cheers @RePeet13 
It does seem a bit quiet around here..
I have the 3 tap kegerator which I'm looking for a simple volume monitoring solution - which kegbot looks to be perfect for (and have all the bits for!)

I've managed to get the tablet to 'see' the arduino via [DroidTerm](https://play.google.com/store/apps/details?id=com.felhr.droidterm) which specifically notes support for the CH340.
When using the serial monitor / blowing through the flow meter I get a stream of characters
![screenshot_2017-12-11-20-10-56](https://user-images.githubusercontent.com/34489394/33905750-7e17bea8-dfe4-11e7-9acf-e170477b3488.png)

But as you've experienced - the kegtab app doesn't recognise the board.

I'm quite keen to get this set up so may need to bite the bullet and buy a genuine board

**Comment by johnnyruz** [comment] 2017-12-18 21:51
Hey everyone,

I started digging into the code to try to make this work with my own knockoff Arduino Nano with the CH340 chip. I think I solved it by just adding the CH340 driver signature to the device_filters.xml file and generating a new apk.

Feel free to try it (at your own risk of course) by downloading the APK here: [kegtab-FixCH340Driver.apk](https://drive.google.com/open?id=1Ta794ivABdbQ3NNoDq5Lw-vgBKLMRToF). There's no additional features or functionality, but hopefully the cheap chips will work. So far I've only tested with the sample output by wiring Pin 12 to Pin 2 on my self-flashed Kegboard.

**Comment by angrypiratebrewing** [comment] 2017-12-18 22:33
Nice work @johnnyruz !
The app recognises there is a kegboard/arduino attached!
(Just when I ordered and paid for a new board.. oh well).

When I blow through the flow meter I get this pop up
![screenshot_2017-12-19-11-24-55](https://user-images.githubusercontent.com/34489394/34131370-2eee83f4-e4b0-11e7-99a9-2dbf33fd763f.png)

Buuuuut here's the problem - in the tap management I can only see/access kegboard.flow0
![screenshot_2017-12-19-11-24-24](https://user-images.githubusercontent.com/34489394/34131394-4e260cf6-e4b0-11e7-910f-455e4d050dec.png)

Ive tried restartint tablet etc etc..
Any ideas?

**Comment by johnnyruz** [comment] 2017-12-19 01:22
Hey angrypirate, thanks for testing.

Are you by any chance using the on-device storage instead of using a Kegbot Server? When using the local storage I have the exact same issue where the tablet seems to recognize data for flow1, but you can't select it from the drop-down. However, when I setup the tablet app pointing to my Kegbot server (actually Kegberry running on a Raspberry Pi 3) I'm able to assign flow0 and flow1 to my 2 taps.

John

**Comment by angrypiratebrewing** [comment] 2017-12-19 01:27
Hey @johnnyruz - yeah, just running on internal storage.

I did think that might be the case, unfortunately I don't have a pi and didn't really want to have to buy one unless absolutely necessary.

I'm going to give running the server from the tablet a shot tonight, following these instructions: https://forum.kegbot.org/t/howto-install-kegbot-server-directly-on-your-android-tablet-no-root/542

**Comment by johnnyruz** [comment] 2017-12-19 01:36
Sounds great, if I get some time I'll see if I can work out how to fix the local issue with the flow meter drop-downs in Local DB mode.

**Comment by RePeet13** [comment] 2017-12-19 15:18
I appreciate you guys working on this, I'm hoping to restart my kegerator adventures with a new keezer build in the next month or so, and getting kegbot back in working shape would be awesome :D

**Comment by angrypiratebrewing** [comment] 2017-12-19 21:12
Having a really hard time getting the server up and running on my tablet, so would really appreciate it if you could check out the issue with assigning the flow meters when running kegbot locally - @johnnyruz 
I'm only after a very simple setup - just wanting to monitor volumes, so the local setup suits me perfectly.


Seems to be an issue installing mysql on my tablet. May as well put up here in case anyone has any ideas.
After asking to set the password I get the error -
Failed to read /proc/cmdline. Ignoring: Permission denied

It doesn't matter if I set a password or not.
![screenshot_2017-12-20-09-07-42](https://user-images.githubusercontent.com/34489394/34178987-0fc96a52-e56e-11e7-8eff-5844832bb200.png)

**Comment by johnnyruz** [comment] 2017-12-20 04:29
Hi @angrypiratebrewing ,

Check out my fork of the project at github.com/johnnyruz/kegbot-android and we can continue this discussion there. I've published a new release that should enable the use of 2 flow meters while in Local DB mode, along with some other minor features that I wanted.

**Comment by angrypiratebrewing** [comment] 2017-12-20 07:32
Hey @johnnyruz - first, mate, you are a legend.
Two taps are assignable and registering flow from my arduino with the CH340. Perfect.
Second, do you have issues activated on that fork? Can't seem to open one.
The problem is I have three taps!
Any chance adding #3?

**Comment by johnnyruz** [comment] 2017-12-20 11:38
@angrypiratebrewing I just enabled issues on my fork so open one there for tracking and I'll try to get another build out today!

**Comment by mik3y** [comment] 2017-12-20 14:13
@johnnyruz PRs are quite welcome here, should be no need to fork! I'll be cutting a new release over the break with some accumulated changes.

**Comment by johnnyruz** [comment] 2017-12-20 16:00
Thanks @mik3y, let me see what I can do about creating some organized PRs for some of my updates. My commits are pretty messy right now.

**Comment by RePeet13** [comment] 2018-01-05 20:23
Just wanted to reiterate that im happy to see activity here once again, soon as I get my kegerator going, you'll start hearing from me with any issues / fixes I find as well

**Comment by mik3y** [comment] 2020-05-18 23:38
resolved in #123 thanks @johnnyruz !

**Closed by mik3y** 2020-05-18 23:38 UTC
